### Obtener todas las categorías
GET http://localhost:3000/api/categoria

### Obtener una categoría por id
GET http://localhost:3000/api/categoria/1

### Publicar una categoría
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
  "id_categoria": "1",
  "nombre": "Bebidas"
}

### Actualizar una categoría
PUT http://localhost:3000/api/categoria/2
Content-Type: application/json

{
  "id_categoria": "2",
  "nombre": "Comidas saladas"
}

### Eliminar una categoría
DELETE http://localhost:3000/api/categoria/2