### Obtener todas las categorías
GET http://localhost:3000/api/categoria

### Crear categoría bebidas
# @name createCategoriaBebidas
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
  "nombre": "bebidas"
}

### Crear categoría comidas
# @name createCategoriaComidas
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
  "nombre": "comidas"
}

### ID
@id = {{createCategoriaBebidas.response.body.data.id}}
@id = {{createCategoriaComidas.response.body.data.id}}

### Obtener una categoría por id
GET http://localhost:3000/api/categoria/{{id}}

### Actualizar una categoría
PUT http://localhost:3000/api/categoria/{{id}}
Content-Type: application/json

{
  "nombre": "comidas"
}

### PATCH a categoria
PATCH http://localhost:3000/api/categoria/{{id}}
Content-Type: application/json

{
  "nombre": "bebidas"
}

### Eliminar una categoría
DELETE http://localhost:3000/api/categoria/4ac64c2c-6a7e-44a4-9e7f-7dc451d3c913