### GET all comentarios
GET http://localhost:3000/api/comentario

### POST a comentario
# @name createComentario
POST http://localhost:3000/api/comentario
Content-Type: application/json

{
  "contenido": "Me encantó este café, el ambiente es muy acogedor y el servicio excelente. Definitivamente volveré pronto.",
  "fecha_publicacion": "2023-01-01",
  "puntuacion": 5,
  "usuario": "25b6e2e5-dbe8-4089-9f8e-4e9a12b7611e"}

### ID
@id = {{createComentario.response.body.data.id}}

### GET one comentario
GET http://localhost:3000/api/comentario/{{id}}

### PUT a comentario
PUT http://localhost:3000/api/comentario/{{id}}
Content-Type: application/json

{
  "contenido": "El café estaba bien, pero el ambiente no era tan agradable como esperaba. El servicio fue un poco lento, pero en general fue una experiencia decente.",
  "fecha_publicacion": "2023-01-01",
  "puntuacion": 3,
  "usuario": "25b6e2e5-dbe8-4089-9f8e-4e9a12b7611e"}

### PATCH a comentario
PATCH http://localhost:3000/api/comentario/{{id}}
Content-Type: application/json

{
  "puntuacion": 4
}

### DELETE a comentario
DELETE http://localhost:3000/api/comentario/{{id}}