### GET all productos
http://localhost:3000/api/producto

### ID
@id = {{createProducto.response.body.data.id}}

### GET one producto
http://localhost:3000/api/producto/{{id}}

### PUT a producto
PUT http://localhost:3000/api/producto/{{id}}
Content-Type: application/json

{
  "nombre": "Café cortado",
  "categoria": 1,
  "descripcion": "Café con leche vaporizada en menor cantidad que el café latte",
  "precio": 3000
}

### POST a producto
# @name createProducto
POST http://localhost:3000/api/producto
Content-Type: application/json

{
    "nombre": "Lemon pie",
    "categoria": "4ac64c2c-6a7e-44a4-9e7f-7dc451d3c913",
    "descripcion": "Tarta con base de galleta y relleno de crema de limón",
    "precio": 3500
}

### PATCH a producto
PATCH http://localhost:3000/api/producto/{{id}}
Content-Type: application/json

{
  "nombre": "Café",
}

### DELETE a producto
@id = {{createProducto.response.body.data.id}}
DELETE http://localhost:3000/api/producto/{{id}}

