### GET all usuarios
http://localhost:3000/api/usuario

### ID
@id = {{createUsuario.response.body.data.id}}

### GET one usuario
http://localhost:3000/api/usuario/{{id}}


### POST a usuario
# @name createUsuario
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
    "nombre": "Camila",
    "apellido": "Salvia",
    "telefono": "654456780",
    "direccion": "Calle Falsa 1234",
    "email": "cami@example.com",
    "password": "password000",
    "esAdmin": true
}
### PUT a usuario
PUT http://localhost:3000/api/usuario/{{id}}
Content-Type: application/json

{
    "nombre": "Camila",
    "apellido": "Salvia",
    "telefono": "123456789",
    "direccion": "Calle Falsa 123",
    "email": "camila.salvia@example.com",
    "password": "password123",
    "esAdmin": false
}


### PATCH a usuario
PATCH http://localhost:3000/api/usuario/{{id}}
Content-Type: application/json

{
    "esAdmin": true
}

### DELETE a usuario
@id = {{createUsuario.response.body.data.id}}
DELETE http://localhost:3000/api/usuario/{{id}}